// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvOhGH9NUO0vPEH-2FoDLqKtPKVA8Li6A',
    appId: '1:628840321993:web:4c08bd678fcf072a3cce18',
    messagingSenderId: '628840321993',
    projectId: 'spotifyflutterclone',
    authDomain: 'spotifyflutterclone.firebaseapp.com',
    storageBucket: 'spotifyflutterclone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHvDxvXZkO3dEXGbgJ5hzYv2xi_atWfPY',
    appId: '1:628840321993:android:ad2e306294bbdf973cce18',
    messagingSenderId: '628840321993',
    projectId: 'spotifyflutterclone',
    storageBucket: 'spotifyflutterclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGlhsML4iyCriyYQ6-dbDrTetXLI0XAAY',
    appId: '1:628840321993:ios:1f3f658d832a80583cce18',
    messagingSenderId: '628840321993',
    projectId: 'spotifyflutterclone',
    storageBucket: 'spotifyflutterclone.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGlhsML4iyCriyYQ6-dbDrTetXLI0XAAY',
    appId: '1:628840321993:ios:1f3f658d832a80583cce18',
    messagingSenderId: '628840321993',
    projectId: 'spotifyflutterclone',
    storageBucket: 'spotifyflutterclone.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvOhGH9NUO0vPEH-2FoDLqKtPKVA8Li6A',
    appId: '1:628840321993:web:6d6cd304a8aa3ab73cce18',
    messagingSenderId: '628840321993',
    projectId: 'spotifyflutterclone',
    authDomain: 'spotifyflutterclone.firebaseapp.com',
    storageBucket: 'spotifyflutterclone.appspot.com',
  );
}
