// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzEHQ6Hl3C51XNlrTAT8W3dS6lcjHUytg',
    appId: '1:823664144424:web:5a286d9472bd1949d0451d',
    messagingSenderId: '823664144424',
    projectId: 'spotify-clone-597c8',
    authDomain: 'spotify-clone-597c8.firebaseapp.com',
    storageBucket: 'spotify-clone-597c8.appspot.com',
    measurementId: 'G-PVXPFX43VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnE4bu9fJ_iJocHeIDaa4VoJJNDflG18E',
    appId: '1:823664144424:android:d64cd34572a7a949d0451d',
    messagingSenderId: '823664144424',
    projectId: 'spotify-clone-597c8',
    storageBucket: 'spotify-clone-597c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFcJY6Qkuu94sWmN4p-ltZPIT_6W8MF4',
    appId: '1:823664144424:ios:3c79da365a80a55bd0451d',
    messagingSenderId: '823664144424',
    projectId: 'spotify-clone-597c8',
    storageBucket: 'spotify-clone-597c8.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlFcJY6Qkuu94sWmN4p-ltZPIT_6W8MF4',
    appId: '1:823664144424:ios:3c79da365a80a55bd0451d',
    messagingSenderId: '823664144424',
    projectId: 'spotify-clone-597c8',
    storageBucket: 'spotify-clone-597c8.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzEHQ6Hl3C51XNlrTAT8W3dS6lcjHUytg',
    appId: '1:823664144424:web:6ba7b7da82bedaefd0451d',
    messagingSenderId: '823664144424',
    projectId: 'spotify-clone-597c8',
    authDomain: 'spotify-clone-597c8.firebaseapp.com',
    storageBucket: 'spotify-clone-597c8.appspot.com',
    measurementId: 'G-C2HH2HSSCH',
  );
}
